collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.09183671
color:
  saturation: 1
  brandStrength: 0.3270676
  lightness: 1
  brandColors:
    - '#FFFFBD'
    - '#635F5C'
    - '#7E8DA0'
    - '#392F26'
    - '#A26F45'
  rhythmicContrast: 0.7857143
layout_spectrum: 0.9554242
name: Nutshell
